version: '3'
services:
  server:
    image: server:dev
    build:
      args:
        NODE_ENV: development
    command: nodemon -L src/index.js
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
      # - ./src:/usr/app/src
      # - ./data:/usr/app/data
  postgres:
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
volumes:
  pgdata: