version: '3'
services:
  bracelet:
    image: bracelet:dev
    build:
      args:
        NODE_ENV: development
    command: nodemon -L src/index.js
    environment:
      NODE_ENV: development
      PRISMA_ENDPOINT: http://prisma:4466/bracelet/dev
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
  postgres:
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
volumes:
  pgdata: